[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Function timeout (10 saniye)
[functions.send-notifications]
  timeout = 10

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/api/vapid-public-key"
  to = "/.netlify/functions/vapid-public-key"
  status = 200

[[redirects]]
  from = "/api/save-subscription"
  to = "/.netlify/functions/save-subscription"
  status = 200

[[redirects]]
  from = "/api/remove-subscription"
  to = "/.netlify/functions/remove-subscription"
  status = 200

[[redirects]]
  from = "/api/send-notifications"
  to = "/.netlify/functions/send-notifications"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"